name: Mirror AetrisVPN Configs

on:
  schedule:
    - cron: '0 * * * *' # Каждый час
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download configs from Google Drive
        run: |
          curl -L "https://docs.google.com/uc?export=download&id=1jYJh5ltgEJ9RiAWuSaG1YrxdCS_2J3M9" -o configs.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add configs.txt
          
          if git diff --staged --quiet; then
            echo "Изменений нет."
          else
            git commit -m "Автообновление подписки"
            git pull --rebase origin main
            git push origin main
          fi
          
      # Этот шаг заставляет GitHub видеть репозиторий как «активный»
      - name: Keepalive
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Поддержание активности воркфлоу"
          git push origin main
