name: Mirror AetrisVPN Configs

on:
  schedule:
    - cron: '15 * * * *'  # Запуск каждый час (чтобы избежать блокировок)
  workflow_dispatch:     # Кнопка для ручного перезапуска

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download configs from Google Drive
        run: |
          # Используем прямой экспорт, который обходит любые HTML-заглушки
          curl -L "https://docs.google.com/uc?export=download&id=1jYJh5ltgEJ9RiAWuSaG1YrxdCS_2J3M9" -o configs.txt

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@://github.com"
          git add configs.txt
          (git diff --quiet && git diff --staged --quiet) || (git commit -m "Автообновление подписки" && git pull --rebase origin main && git push origin main)
